# Generated by Django 4.2.7 on 2023-11-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoventa',
            name='vehvnt_modelo',
            field=models.CharField(default='Desconocido', max_length=30),
        ),
    ]
