# Generated by Django 4.2.5 on 2023-11-03 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appmanager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                ("cargo_cod", models.AutoField(primary_key=True, serialize=False)),
                ("cargo_nombre", models.CharField(max_length=30)),
                ("cargo_descripcion", models.TextField()),
                ("cargo_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CotizacionReparacion",
            fields=[
                ("cotrep_cod", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cotrep_precioreparacion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cotrep_observaciones", models.TextField()),
                ("cotrep_fecharealizada", models.DateTimeField()),
                ("cotrep_estado", models.BooleanField(default=True)),
                ("cotrep_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CotizacionRepuestos",
            fields=[
                ("cotrepues_cod", models.AutoField(primary_key=True, serialize=False)),
                ("cotrepues_preciotemporal", models.IntegerField()),
                ("cotrepues_fecharealizada", models.DateTimeField()),
                ("cotrepues_estado", models.BooleanField(default=True)),
                ("cotrepues_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CotizacionVehiculo",
            fields=[
                ("cotven_cod", models.AutoField(primary_key=True, serialize=False)),
                ("cotven_fecharealizada", models.DateTimeField()),
                ("cotven_estado", models.BooleanField(default=True)),
                ("cotven_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                ("codfac", models.AutoField(primary_key=True, serialize=False)),
                (
                    "codfac_subtotal",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("codfac_iva", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "codfac_descuento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "codfac_precioTotal",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("codfac_fecharealizada", models.DateField()),
                ("codfac_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                ("inv_cod", models.AutoField(primary_key=True, serialize=False)),
                ("inv_nombre", models.CharField(max_length=30)),
                ("inv_categoria", models.CharField(max_length=50)),
                ("inv_descripcion", models.TextField()),
                (
                    "inv_precioneto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("inv_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InventarioPorSucursal",
            fields=[
                ("invsus_cod", models.AutoField(primary_key=True, serialize=False)),
                ("invss_existencias", models.IntegerField()),
                ("inv_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "invssus_codigo_inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appmanager.inventario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("menu_id", models.AutoField(primary_key=True, serialize=False)),
                ("menu_nombre", models.CharField(max_length=30)),
                ("menu_descripcion", models.TextField(blank=True, null=True)),
                ("menu_estado", models.BooleanField(default=True)),
                ("menu_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrdenTrabajo",
            fields=[
                ("orden_cod", models.AutoField(primary_key=True, serialize=False)),
                ("orden_observacion", models.TextField()),
                ("orden_estado", models.BooleanField(default=True)),
                ("orden_fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("orden_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Permiso",
            fields=[
                ("permiso_id", models.AutoField(primary_key=True, serialize=False)),
                ("permiso_read", models.BooleanField(default=False)),
                ("permiso_write", models.BooleanField(default=False)),
                ("permiso_update", models.BooleanField(default=False)),
                ("permiso_delete", models.BooleanField(default=False)),
                ("permiso_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "permiso_cod_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appmanager.menu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("per_cod", models.AutoField(primary_key=True, serialize=False)),
                ("per_apellido", models.CharField(max_length=50)),
                ("per_nombre", models.CharField(max_length=50)),
                ("per_tipo_doc", models.CharField(max_length=10)),
                ("per_numero_doc", models.CharField(max_length=20)),
                ("per_correo", models.EmailField(max_length=50)),
                ("per_telefono", models.CharField(max_length=20)),
                ("per_vigente", models.BooleanField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PersonaXCargo",
            fields=[
                ("perxcargo_cod", models.AutoField(primary_key=True, serialize=False)),
                ("perxcargo_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "perxcargo_cargo_cod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appmanager.cargo",
                    ),
                ),
                (
                    "perxcargo_persona_cod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appmanager.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepuestoVenta",
            fields=[
                ("repvnt_cod", models.AutoField(primary_key=True, serialize=False)),
                ("repvnt_descripcion", models.TextField()),
                ("repvnt_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "repvnt_inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appmanager.inventarioporsucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("rol_cod", models.AutoField(primary_key=True, serialize=False)),
                ("rol_nombre", models.CharField(max_length=50)),
                ("rol_descripcion", models.TextField(blank=True, null=True)),
                ("rol_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                ("sucursal_cod", models.AutoField(primary_key=True, serialize=False)),
                ("sucursal_nombre", models.CharField(max_length=50)),
                ("sucursal_ubicacion", models.CharField(max_length=100)),
                ("sucursal_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "sucursal_cod_gerente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appmanager.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("usuario_id", models.AutoField(primary_key=True, serialize=False)),
                ("usuario_nickname", models.CharField(max_length=20)),
                ("usuario_correo", models.EmailField(max_length=40)),
                ("usuario_password", models.CharField(max_length=20)),
                (
                    "usuario_ultima_conexion",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("usuario_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "usuario_cod_rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="appmanager.rol"
                    ),
                ),
                (
                    "usuario_cod_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appmanager.sucursal",
                    ),
                ),
                (
                    "usuario_persona_cod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appmanager.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiculoReparacion",
            fields=[
                ("vehrep_cod", models.AutoField(primary_key=True, serialize=False)),
                ("vehrep_placa", models.CharField(max_length=20)),
                ("vehrep_marca", models.CharField(max_length=30)),
                ("vehrep_color", models.CharField(max_length=30)),
                ("vehrep_enReparacion", models.BooleanField(default=False)),
                ("vehrep_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "vehrep_dueño",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appmanager.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiculoVenta",
            fields=[
                ("vehvnt_cod", models.AutoField(primary_key=True, serialize=False)),
                ("vehvnt_placa", models.CharField(max_length=10)),
                ("vehvnt_marca", models.CharField(max_length=30)),
                ("vehvnt_color", models.CharField(max_length=30)),
                ("vehvnt_anio", models.CharField(max_length=30)),
                (
                    "vehvnt_precioneto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("vehvnt_disponible", models.BooleanField(default=True)),
                ("vehvnt_vigente", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "vehvnt_cod_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appmanager.sucursal",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Admin",),
        migrations.AddField(
            model_name="personaxcargo",
            name="perxcargo_sucursal_cod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appmanager.sucursal"
            ),
        ),
        migrations.AddField(
            model_name="permiso",
            name="permiso_cod_rol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appmanager.rol"
            ),
        ),
        migrations.AddField(
            model_name="ordentrabajo",
            name="orden_encargado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appmanager.personaxcargo",
            ),
        ),
        migrations.AddField(
            model_name="ordentrabajo",
            name="orden_vehiculoreparacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appmanager.vehiculoreparacion",
            ),
        ),
        migrations.AddField(
            model_name="inventarioporsucursal",
            name="invsus_sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appmanager.sucursal"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="codfac_cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appmanager.persona"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="codfac_cotizacion_vehiculonuevo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appmanager.cotizacionvehiculo",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="codfac_reparacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appmanager.cotizacionreparacion",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="codfac_repuestos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appmanager.cotizacionrepuestos",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="codfac_vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appmanager.personaxcargo",
            ),
        ),
        migrations.AddField(
            model_name="cotizacionvehiculo",
            name="cotven_cod_vehiculo_nuevo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appmanager.vehiculoventa",
            ),
        ),
        migrations.AddField(
            model_name="cotizacionrepuestos",
            name="cotrepues_repuestocod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appmanager.repuestoventa",
            ),
        ),
        migrations.AddField(
            model_name="cotizacionreparacion",
            name="cotrep_orden_trabajo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appmanager.ordentrabajo",
            ),
        ),
    ]
