# Generated by Django 4.2.7 on 2023-11-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInventario',
            fields=[
                ('categoriainv', models.AutoField(primary_key=True, serialize=False)),
                ('categoriainv_nombre', models.CharField(max_length=100)),
                ('categoriainv_vigente', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventario',
            name='inv_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmanager.categoriainventario'),
        ),
    ]
