# Generated by Django 4.2.6 on 2023-11-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaxcargo',
            name='perxcargo_rol_cod',
        ),
    ]
