# Generated by Django 4.2.7 on 2023-11-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionreparacion',
            name='cotrep_estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cotizacionrepuestos',
            name='cotrepues_estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cotizacionvehiculo',
            name='cotven_estado',
            field=models.BooleanField(default=False),
        ),
    ]
