# Generated by Django 4.2.6 on 2023-11-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0002_alter_rol_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cod_rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='appmanager.rol'),
        ),
    ]
