# Generated by Django 4.2.5 on 2023-11-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appmanager", "0002_cargo_cotizacionreparacion_cotizacionrepuestos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("username", models.CharField(default="", max_length=50)),
                ("email", models.EmailField(default="", max_length=30)),
                ("password", models.CharField(default="", max_length=20)),
                ("phone", models.CharField(default="", max_length=20)),
                ("ndoc", models.CharField(default="", max_length=20)),
            ],
        ),
    ]
