# Generated by Django 4.2.7 on 2023-11-20 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0002_categoriainventario_alter_inventario_inv_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventarioporsucursal',
            old_name='invssus_codigo_inventario',
            new_name='invsus_codigo_inventario',
        ),
        migrations.RenameField(
            model_name='inventarioporsucursal',
            old_name='invss_existencias',
            new_name='invsus_existencias',
        ),
        migrations.RenameField(
            model_name='inventarioporsucursal',
            old_name='inv_vigente',
            new_name='invsus_vigente',
        ),
    ]
