# Generated by Django 4.2.7 on 2023-11-21 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0003_rename_invssus_codigo_inventario_inventarioporsucursal_invsus_codigo_inventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='permiso_cod_menu',
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='permiso_cod_rol',
        ),
        migrations.AlterField(
            model_name='vehiculoreparacion',
            name='vehrep_dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
    ]
